In [1]:
def my_func(x):
    return 2*x

In [2]:
[my_func(i) for i in range(5)]

[0, 2, 4, 6, 8]

In [4]:
value = 'cat' if 2>1 else 'dog'
value

'cat'

In [5]:
L = [1,2,3,4,5,6]
[i if i <= 5 else 5 for i in L]

[1, 2, 3, 4, 5, 5]

In [6]:
my_func = lambda x: 2*x

In [8]:
my_func(3)

6

In [9]:
list(map(lambda x: 2*x, range(5)))

[0, 2, 4, 6, 8]

In [10]:
list(map(my_func, range(10)))

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [11]:
list(map(lambda x, y: str(x)+'_'+y, range(5), list('abcde')))

['0_a', '1_b', '2_c', '3_d', '4_e']

In [12]:
L1, L2, L3 = list('abc'), list('def'), list('hij')

In [13]:
dict(zip(L1, L2))

{'a': 'd', 'b': 'e', 'c': 'f'}

In [14]:
import numpy as np

In [15]:
np.array([1,2,3])

array([1, 2, 3])

In [16]:
np.linspace(1,5,11)

array([1. , 1.4, 1.8, 2.2, 2.6, 3. , 3.4, 3.8, 4.2, 4.6, 5. ])

In [17]:
np.arange(1,5,2)

array([1, 3])

In [18]:
np.zeros((2,3)) # 传入元组表示各维度大小

array([[0., 0., 0.],
       [0., 0., 0.]])

In [21]:
np.random.rand(3) # 0-1

array([0.73833839, 0.4746493 , 0.49691071])

In [22]:
np.random.rand(3, 3)

array([[0.60276267, 0.34785149, 0.6823553 ],
       [0.64494997, 0.56786515, 0.98481929],
       [0.1302328 , 0.65906078, 0.2292173 ]])

In [23]:
a, b = 5, 15
(b-a) * np.random.rand(3) + a

array([ 9.96622148, 10.17199331,  6.93375302])

In [24]:
np.random.uniform(5, 15, 3)

array([6.37583103, 6.19435313, 9.17629151])

In [25]:
np.random.randn(10)

array([-1.05637681, -0.75978084, -0.93731725, -0.35783066, -0.21912932,
        0.9846539 ,  0.13484884,  1.10685793, -1.41068785,  0.49665129])

In [26]:
np.random.randn(2, 2)

array([[ 1.20930881,  0.51839852],
       [-0.80483812, -1.08780883]])

In [27]:
sigma, mu = 2.5, 3
mu + np.random.randn(3)*sigma

array([4.24999567, 4.1089547 , 5.13643225])

In [28]:
np.random.normal(3, 2.5, 3)

array([0.99552744, 0.9353675 , 7.01179458])

In [29]:
low, high, size = 5, 15, (2,2) # 生成5到14的随机整数
np.random.randint(low, high, size)

array([[11, 14],
       [ 8, 12]])

In [30]:
my_list = ['a', 'b', 'c', 'd']
np.random.choice(my_list, 2, replace=False, p=[0.1, 0.7, 0.1 ,0.1])

array(['b', 'd'], dtype='<U1')

In [31]:
np.random.choice(my_list, (3,3))

array([['b', 'd', 'd'],
       ['b', 'c', 'a'],
       ['d', 'b', 'b']], dtype='<U1')

In [32]:
np.random.seed(0)
np.random.rand()

0.5488135039273248

In [33]:
np.zeros((2,3)).T

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [35]:
np.r_[np.array([0,0]),np.zeros(2)]

array([0., 0., 0., 0.])

In [36]:
np.c_[np.array([0,0]),np.zeros((2,3))]

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [39]:
target = np.arange(9).reshape(3,3)
target

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [46]:
slice = target[:-1, [0, 2]]
slice

array([[0, 2],
       [3, 5]])

In [44]:
slice[0,1]

2

In [42]:
slice.sum(0)

array([3, 7])

In [48]:
slice.sum(1)

array([2, 8])

# Chapter 2. Pandas

In [49]:
import numpy as np
import pandas as pd

In [50]:
pd.__version__

'1.1.4'

In [53]:
df_csv = pd.read_csv('../data/my_csv.csv') # ../ 上一层文件夹
df_csv

col1 col2  col3    col4      col5
0     2    a   1.4   apple  2020/1/1
1     3    b   3.4  banana  2020/1/2
2     6    c   2.5  orange  2020/1/5
3     5    d   3.2   lemon  2020/1/7

In [54]:
df_txt = pd.read_table('../data/my_table.txt')
df_txt

col1 col2  col3             col4
0     2    a   1.4   apple 2020/1/1
1     3    b   3.4  banana 2020/1/2
2     6    c   2.5  orange 2020/1/5
3     5    d   3.2   lemon 2020/1/7

In [55]:
df_excel = pd.read_excel('../data/my_excel.xlsx')
df_excel

col1 col2  col3    col4      col5
0     2    a   1.4   apple  2020/1/1
1     3    b   3.4  banana  2020/1/2
2     6    c   2.5  orange  2020/1/5
3     5    d   3.2   lemon  2020/1/7

In [56]:
data = [[1, 'a', 1.2], [2, 'b', 2.2], [3, 'c', 3.2]]
df = pd.DataFrame(data = data,
                  index = ['row_%d'%i for i in range(3)],
                  columns=['col_0', 'col_1', 'col_2'])
df

col_0 col_1  col_2
row_0      1     a    1.2
row_1      2     b    2.2
row_2      3     c    3.2

In [57]:
df = pd.DataFrame(data = {'col_0': [1,2,3],
                          'col_1':list('abc'),
                          'col_2': [1.2, 2.2, 3.2]},
                  index = ['row_%d'%i for i in range(3)])
df

col_0 col_1  col_2
row_0      1     a    1.2
row_1      2     b    2.2
row_2      3     c    3.2

In [58]:
df[['col_0', 'col_1']]

col_0 col_1
row_0      1     a
row_1      2     b
row_2      3     c

In [59]:
df = pd.read_csv('../data/learn_pandas.csv')
df.columns

Index(['School', 'Grade', 'Name', 'Gender', 'Height', 'Weight', 'Transfer',
       'Test_Number', 'Test_Date', 'Time_Record'],
      dtype='object')

In [60]:
df = df[df.columns[:7]]

In [61]:
df.head(5)

School      Grade            Name  Gender  Height  \
0  Shanghai Jiao Tong University   Freshman    Gaopeng Yang  Female   158.9   
1              Peking University   Freshman  Changqiang You    Male   166.5   
2  Shanghai Jiao Tong University     Senior         Mei Sun    Male   188.9   
3               Fudan University  Sophomore    Xiaojuan Sun  Female     NaN   
4               Fudan University  Sophomore     Gaojuan You    Male   174.0   

   Weight Transfer  
0    46.0        N  
1    70.0        N  
2    89.0        N  
3    41.0        N  
4    74.0        N

In [62]:
df.tail(5)

School      Grade            Name  Gender  Height  \
195               Fudan University     Junior    Xiaojuan Sun  Female   153.9   
196            Tsinghua University     Senior         Li Zhao  Female   160.9   
197  Shanghai Jiao Tong University     Senior  Chengqiang Chu  Female   153.9   
198  Shanghai Jiao Tong University     Senior   Chengmei Shen    Male   175.3   
199            Tsinghua University  Sophomore     Chunpeng Lv    Male   155.7   

     Weight Transfer  
195    46.0        N  
196    50.0        N  
197    45.0        N  
198    71.0        N  
199    51.0        N

In [63]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   School    200 non-null    object 
 1   Grade     200 non-null    object 
 2   Name      200 non-null    object 
 3   Gender    200 non-null    object 
 4   Height    183 non-null    float64
 5   Weight    189 non-null    float64
 6   Transfer  188 non-null    object 
dtypes: float64(2), object(5)
memory usage: 11.1+ KB


In [67]:
df['Gender'].replace({'Female':0, 'Male':1}).head()

0    0
1    1
2    1
3    0
4    1
Name: Gender, dtype: int64

School      Grade            Name  Gender  Height  \
0    Shanghai Jiao Tong University   Freshman    Gaopeng Yang  Female   158.9   
1                Peking University   Freshman  Changqiang You    Male   166.5   
2    Shanghai Jiao Tong University     Senior         Mei Sun    Male   188.9   
3                 Fudan University  Sophomore    Xiaojuan Sun  Female     NaN   
4                 Fudan University  Sophomore     Gaojuan You    Male   174.0   
..                             ...        ...             ...     ...     ...   
195               Fudan University     Junior    Xiaojuan Sun  Female   153.9   
196            Tsinghua University     Senior         Li Zhao  Female   160.9   
197  Shanghai Jiao Tong University     Senior  Chengqiang Chu  Female   153.9   
198  Shanghai Jiao Tong University     Senior   Chengmei Shen    Male   175.3   
199            Tsinghua University  Sophomore     Chunpeng Lv    Male   155.7   

     Weight Transfer  
0      46.0        N  
1      70.0        N  
2      89.0        N  
3      41.0        N  
4      74.0        N  
..      ...      ...  
195    46.0        N  
196    50.0        N  
197    45.0        N  
198    71.0        N  
199    51.0        N  

[200 rows x 7 columns]

In [69]:
df_demo = df[['Grade', 'Name', 'Height', 'Weight']].set_index(['Grade','Name'])
df_demo.head(10)

Height  Weight
Grade     Name                          
Freshman  Gaopeng Yang     158.9    46.0
          Changqiang You   166.5    70.0
Senior    Mei Sun          188.9    89.0
Sophomore Xiaojuan Sun       NaN    41.0
          Gaojuan You      174.0    74.0
Freshman  Xiaoli Qian      158.0    51.0
          Qiang Chu        162.5    52.0
Junior    Gaoqiang Qian    161.9    50.0
Freshman  Changli Zhang    163.0    48.0
Junior    Juan Xu          164.8     NaN

In [70]:
df_demo.sort_values('Height', ascending=False).head()

Height  Weight
Grade    Name                         
Senior   Xiaoqiang Qin   193.9    79.0
         Mei Sun         188.9    89.0
         Gaoli Zhao      186.5    83.0
Freshman Qiang Han       185.3    87.0
Senior   Qiang Zheng     183.9    87.0

In [ ]:
de_demo = df[['height', 'weight']]

def my_mean(x):
    res = x.mean()

# Chapter 3. Indexing

In [71]:
df = pd.read_csv('../data/learn_pandas.csv', usecols = ['School', 'Grade', 'Name', 'Gender', 'Weight', 'Transfer'])
df['Name'].head()

0      Gaopeng Yang
1    Changqiang You
2           Mei Sun
3      Xiaojuan Sun
4       Gaojuan You
Name: Name, dtype: object

In [72]:
df_demo = df.set_index('Name')
df_demo.head()

School      Grade  Gender  Weight  \
Name                                                                       
Gaopeng Yang    Shanghai Jiao Tong University   Freshman  Female    46.0   
Changqiang You              Peking University   Freshman    Male    70.0   
Mei Sun         Shanghai Jiao Tong University     Senior    Male    89.0   
Xiaojuan Sun                 Fudan University  Sophomore  Female    41.0   
Gaojuan You                  Fudan University  Sophomore    Male    74.0   

               Transfer  
Name                     
Gaopeng Yang          N  
Changqiang You        N  
Mei Sun               N  
Xiaojuan Sun          N  
Gaojuan You           N

In [75]:
df_demo.loc['Qiang Sun'] # 多个人叫此名字

School      Grade  Gender  Weight Transfer
Name                                                                        
Qiang Sun            Tsinghua University     Junior  Female    53.0        N
Qiang Sun            Tsinghua University  Sophomore  Female    40.0        N
Qiang Sun  Shanghai Jiao Tong University     Junior  Female     NaN        N

In [76]:
df_demo.loc['Qiang Sun', 'School'] # 返回Series

Name
Qiang Sun              Tsinghua University
Qiang Sun              Tsinghua University
Qiang Sun    Shanghai Jiao Tong University
Name: School, dtype: object

In [78]:
df_loc_slice_demo = df_demo.copy()
df_loc_slice_demo.index = range(df_demo.shape[0],0,-1)
df_loc_slice_demo

School      Grade  Gender  Weight Transfer
200  Shanghai Jiao Tong University   Freshman  Female    46.0        N
199              Peking University   Freshman    Male    70.0        N
198  Shanghai Jiao Tong University     Senior    Male    89.0        N
197               Fudan University  Sophomore  Female    41.0        N
196               Fudan University  Sophomore    Male    74.0        N
..                             ...        ...     ...     ...      ...
5                 Fudan University     Junior  Female    46.0        N
4              Tsinghua University     Senior  Female    50.0        N
3    Shanghai Jiao Tong University     Senior  Female    45.0        N
2    Shanghai Jiao Tong University     Senior    Male    71.0        N
1              Tsinghua University  Sophomore    Male    51.0        N

[200 rows x 5 columns]

In [81]:
df_loc_slice_demo.loc[5:3] # 没有返回，说明不是整数位置切片

School   Grade  Gender  Weight Transfer
5               Fudan University  Junior  Female    46.0        N
4            Tsinghua University  Senior  Female    50.0        N
3  Shanghai Jiao Tong University  Senior  Female    45.0        N

In [86]:
df_demo[df_demo.Weight>70].head()

School      Grade Gender  Weight  \
Name                                                                     
Mei Sun        Shanghai Jiao Tong University     Senior   Male    89.0   
Gaojuan You                 Fudan University  Sophomore   Male    74.0   
Xiaopeng Zhou  Shanghai Jiao Tong University   Freshman   Male    74.0   
Xiaofeng Sun             Tsinghua University     Senior   Male    71.0   
Qiang Zheng    Shanghai Jiao Tong University     Senior   Male    87.0   

              Transfer  
Name                    
Mei Sun              N  
Gaojuan You          N  
Xiaopeng Zhou        N  
Xiaofeng Sun         N  
Qiang Zheng          N

In [87]:
df_demo.loc[df_demo.Grade.isin(['Freshman', 'Senior'])].head()

School     Grade  Gender  Weight  \
Name                                                                      
Gaopeng Yang    Shanghai Jiao Tong University  Freshman  Female    46.0   
Changqiang You              Peking University  Freshman    Male    70.0   
Mei Sun         Shanghai Jiao Tong University    Senior    Male    89.0   
Xiaoli Qian               Tsinghua University  Freshman  Female    51.0   
Qiang Chu       Shanghai Jiao Tong University  Freshman  Female    52.0   

               Transfer  
Name                     
Gaopeng Yang          N  
Changqiang You        N  
Mei Sun               N  
Xiaoli Qian           N  
Qiang Chu             N

In [91]:
df_demo.iloc[(df_demo.Weight>80).values].head()

School      Grade Gender  Weight  \
Name                                                                      
Mei Sun         Shanghai Jiao Tong University     Senior   Male    89.0   
Qiang Zheng     Shanghai Jiao Tong University     Senior   Male    87.0   
Qiang Han                   Peking University   Freshman   Male    87.0   
Chengpeng Zhou               Fudan University     Senior   Male    81.0   
Feng Han        Shanghai Jiao Tong University  Sophomore   Male    82.0   

               Transfer  
Name                     
Mei Sun               N  
Qiang Zheng           N  
Qiang Han             N  
Chengpeng Zhou        N  
Feng Han              N

In [92]:
condition_1_1 = df_demo.School == 'Fudan University'
condition_1_2 = df_demo.Grade == 'Senior'
condition_1_3 = df_demo.Weight > 70
condition_1 = condition_1_1 & condition_1_2 & condition_1_3
condition_2_1 = df_demo.School == 'Peking University'
condition_2_2 = df_demo.Grade == 'Senior'
condition_2_3 = df_demo.Weight > 80
condition_2 = condition_2_1 & (~condition_2_2) & condition_2_3
df_demo.loc[condition_1 | condition_2]

School     Grade Gender  Weight Transfer
Name                                                               
Qiang Han       Peking University  Freshman   Male    87.0        N
Chengpeng Zhou   Fudan University    Senior   Male    81.0        N
Changpeng Zhao  Peking University  Freshman   Male    83.0        N
Chengpeng Qian   Fudan University    Senior   Male    73.0        Y

In [93]:
np.random.seed(0)
multi_index = pd.MultiIndex.from_product([list('ABCD'), df.Gender.unique()], names=('School', 'Gender'))
multi_column = pd.MultiIndex.from_product([['Height', 'Weight'], df.Grade.unique()], names=('Indicator', 'Grade'))
df_multi = pd.DataFrame(np.c_[(np.random.randn(8,4)*5 + 163).tolist(), (np.random.randn(8,4)*5 + 65).tolist()],
                        index = multi_index, columns = multi_column).round(1)
df_multi

Indicator       Height                           Weight                   \
Grade         Freshman Senior Sophomore Junior Freshman Senior Sophomore   
School Gender                                                              
A      Female    171.8  165.0     167.9  174.2     60.6   55.1      63.3   
       Male      172.3  158.1     167.8  162.2     71.2   71.0      63.1   
B      Female    162.5  165.1     163.7  170.3     59.8   57.9      56.5   
       Male      166.8  163.6     165.2  164.7     62.5   62.8      58.7   
C      Female    170.5  162.0     164.6  158.7     56.9   63.9      60.5   
       Male      150.2  166.3     167.3  159.3     62.4   59.1      64.9   
D      Female    174.3  155.7     163.2  162.1     65.3   66.5      61.8   
       Male      170.7  170.3     163.8  164.9     61.6   63.2      60.9   

Indicator             
Grade         Junior  
School Gender         
A      Female   65.8  
       Male     63.5  
B      Female   74.8  
       Male     68.9  
C      Female   66.9  
       Male     67.1  
D      Female   63.2  
       Male     56.4

In [94]:
df_multi.index.names

FrozenList(['School', 'Gender'])

In [95]:
df_multi.columns.names

FrozenList(['Indicator', 'Grade'])

In [96]:
df_multi.index.values

array([('A', 'Female'), ('A', 'Male'), ('B', 'Female'), ('B', 'Male'),
       ('C', 'Female'), ('C', 'Male'), ('D', 'Female'), ('D', 'Male')],
      dtype=object)

In [97]:
df_multi.columns.values

array([('Height', 'Freshman'), ('Height', 'Senior'),
       ('Height', 'Sophomore'), ('Height', 'Junior'),
       ('Weight', 'Freshman'), ('Weight', 'Senior'),
       ('Weight', 'Sophomore'), ('Weight', 'Junior')], dtype=object)

In [98]:
df_multi = df.set_index(['School', 'Grade'])
df_multi.head()

Name  Gender  Weight  \
School                        Grade                                       
Shanghai Jiao Tong University Freshman     Gaopeng Yang  Female    46.0   
Peking University             Freshman   Changqiang You    Male    70.0   
Shanghai Jiao Tong University Senior            Mei Sun    Male    89.0   
Fudan University              Sophomore    Xiaojuan Sun  Female    41.0   
                              Sophomore     Gaojuan You    Male    74.0   

                                        Transfer  
School                        Grade               
Shanghai Jiao Tong University Freshman         N  
Peking University             Freshman         N  
Shanghai Jiao Tong University Senior           N  
Fudan University              Sophomore        N  
                              Sophomore        N

In [100]:
df_sorted = df_multi.sort_index()
df_sorted

Name  Gender  Weight Transfer
School              Grade                                              
Fudan University    Freshman   Changqiang Yang  Female    49.0        N
                    Freshman      Gaoqiang Qin  Female    63.0        N
                    Freshman      Gaofeng Zhao  Female    43.0        N
                    Freshman      Yanquan Wang  Female    55.0        N
                    Freshman         Feng Wang    Male    74.0        N
...                                        ...     ...     ...      ...
Tsinghua University Sophomore        Feng Qian  Female    43.0        N
                    Sophomore           Li Qin    Male    76.0        N
                    Sophomore      Yanjuan You    Male    55.0        N
                    Sophomore   Xiaoqiang Qian    Male    73.0        N
                    Sophomore      Chunpeng Lv    Male    51.0        N

[200 rows x 4 columns]

In [101]:
df_sorted.loc[('Fudan University', 'Junior')].head()

Name  Gender  Weight Transfer
School           Grade                                         
Fudan University Junior      Yanli You  Female    48.0        N
                 Junior  Chunqiang Chu    Male    72.0        N
                 Junior   Changfeng Lv    Male    76.0        N
                 Junior     Yanjuan Lv  Female    49.0      NaN
                 Junior  Gaoqiang Zhou  Female    43.0        N

In [104]:
df_new = pd.DataFrame({'A':list('aacd'), 'B':list('PQRT'), 'C':[1,2,3,4]})
df_new

A  B  C
0  a  P  1
1  a  Q  2
2  c  R  3
3  d  T  4

In [105]:
df_new.set_index('A')

B  C
A      
a  P  1
a  Q  2
c  R  3
d  T  4

In [106]:
my_index = pd.Series(list('WXYZ'), name='D')
df_new = df_new.set_index(['A', my_index])
df_new

B  C
A D      
a W  P  1
  X  Q  2
c Y  R  3
d Z  T  4

In [107]:
df_new.reset_index(['D'], drop=True)

B  C
A      
a  P  1
a  Q  2
c  R  3
d  T  4

In [126]:
df_new.reset_index()

A  D  B  C
0  a  W  P  1
1  a  X  Q  2
2  c  Y  R  3
3  d  Z  T  4

1. 分别只使用`query`和`loc`选出年龄不超过四十岁且工作部门为`Dairy`或`Bakery`的男性。
2. 选出员工`ID`号 为奇数所在行的第1、第3和倒数第2列。
3. 按照以下步骤进行索引操作：

* 把后三列设为索引后交换内外两层
* 恢复中间层索引
* 修改外层索引名为`Gender`
* 用下划线合并两层行索引
* 把行索引拆分为原状态
* 修改索引名为原表名称
* 恢复默认索引并将列保持为原表的相对位置

In [110]:
df = pd.read_csv('../data/company.csv')
df.head(5)

EmployeeID birthdate_key  age  city_name department           job_title  \
0        1318      1/3/1954   61  Vancouver  Executive                 CEO   
1        1319      1/3/1957   58  Vancouver  Executive           VP Stores   
2        1320      1/2/1955   60  Vancouver  Executive       Legal Counsel   
3        1321      1/2/1959   56  Vancouver  Executive  VP Human Resources   
4        1322      1/9/1958   57  Vancouver  Executive          VP Finance   

  gender  
0      M  
1      F  
2      F  
3      M  
4      M

In [125]:
condition1 = df['age'] <= 40
condition2 = df['department'].isin(['Dairy', 'Bakery'])
condition3 = df['gender'] == 'M'

df.loc[condition1 & condition2 & condition3].head(5)

EmployeeID birthdate_key  age city_name department     job_title gender
3611        5791     1/14/1975   40   Kelowna      Dairy  Dairy Person      M
3613        5793     1/22/1975   40  Richmond     Bakery         Baker      M
3615        5795     1/30/1975   40   Nanaimo      Dairy  Dairy Person      M
3617        5797      2/3/1975   40   Nanaimo      Dairy  Dairy Person      M
3618        5798      2/4/1975   40    Surrey      Dairy  Dairy Person      M

In [135]:
condition1 = df['EmployeeID']%2 == 1
df.iloc[(condition1).values, [0, 2, -2]].head(5)

EmployeeID  age                      job_title
1        1319   58                      VP Stores
3        1321   56             VP Human Resources
5        1323   53      Exec Assistant, VP Stores
6        1325   51  Exec Assistant, Legal Counsel
8        1329   48                  Store Manager

In [142]:
df_op = df.copy()
df_op = df_op.set_index(df_op.columns[-3:].tolist()).swaplevel(0,2,axis=0)
df_op = df_op.reset_index(level=1)
df_op = df_op.rename_axis(index={'gender':'Gender'})
df_op.index = df_op.index.map(lambda x:'_'.join(x))
df_op.index = df_op.index.map(lambda x:tuple(x.split('_')))
df_op = df_op.rename_axis(index=['gender', 'department'])
df_op = df_op.reset_index().reindex(df.columns, axis=1)
df_op.equals(df)

True

In [162]:
df = pd.read_csv('../data/chocolate.csv')
df.head()

Company  Review\r\nDate Cocoa\r\nPercent Company\r\nLocation  Rating
0  A. Morin            2016              63%              France    3.75
1  A. Morin            2015              70%              France    2.75
2  A. Morin            2015              70%              France    3.00
3  A. Morin            2015              70%              France    3.50
4  A. Morin            2015              70%              France    3.50

In [163]:
df.columns = [' '.join(i.split('\n')) for i in df.columns]
df.columns = [' '.join(i.split('\r')) for i in df.columns]
df.head(3)

Company  Review  Date Cocoa  Percent Company  Location  Rating
0  A. Morin          2016            63%            France    3.75
1  A. Morin          2015            70%            France    2.75
2  A. Morin          2015            70%            France    3.00

In [164]:
condition1 = df['Rating']<3
condition1

0       False
1        True
2       False
3       False
4       False
        ...  
1790    False
1791    False
1792    False
1793    False
1794    False
Name: Rating, Length: 1795, dtype: bool

In [165]:
df['Cocoa  Percent'] = df['Cocoa  Percent'].apply(lambda x: float(x[:-1])/100)
condition2 = df['Cocoa  Percent'] > df['Cocoa  Percent'].median()
condition2

0       False
1       False
2       False
3       False
4       False
        ...  
1790    False
1791    False
1792    False
1793    False
1794    False
Name: Cocoa  Percent, Length: 1795, dtype: bool

In [166]:
df.loc[condition1 & condition2]

Company  Review  Date  Cocoa  Percent Company  Location  \
33    Akesson's (Pralus)          2010            0.75       Switzerland   
34    Akesson's (Pralus)          2010            0.75       Switzerland   
36         Alain Ducasse          2014            0.75            France   
38         Alain Ducasse          2013            0.75            France   
39         Alain Ducasse          2013            0.75            France   
...                  ...           ...             ...               ...   
1736    Wilkie's Organic          2013            0.89           Ireland   
1738    Wilkie's Organic          2013            0.75           Ireland   
1741      Willie's Cacao          2013            1.00              U.K.   
1769       Zart Pralinen          2016            0.85           Austria   
1778              Zotter          2014            0.80           Austria   

      Rating  
33      2.75  
34      2.75  
36      2.75  
38      2.50  
39      2.50  
...      ...  
1736    2.75  
1738    2.75  
1741    2.25  
1769    2.75  
1778    2.75  

[239 rows x 5 columns]

In [172]:
res = df.set_index(['Review  Date', 'Company  Location'])

In [1]:
import numpy as np
import pandas as pd

In [3]:
df = pd.read_csv('../data/learn_pandas.csv')
df

School      Grade            Name  Gender  Height  \
0    Shanghai Jiao Tong University   Freshman    Gaopeng Yang  Female   158.9   
1                Peking University   Freshman  Changqiang You    Male   166.5   
2    Shanghai Jiao Tong University     Senior         Mei Sun    Male   188.9   
3                 Fudan University  Sophomore    Xiaojuan Sun  Female     NaN   
4                 Fudan University  Sophomore     Gaojuan You    Male   174.0   
..                             ...        ...             ...     ...     ...   
195               Fudan University     Junior    Xiaojuan Sun  Female   153.9   
196            Tsinghua University     Senior         Li Zhao  Female   160.9   
197  Shanghai Jiao Tong University     Senior  Chengqiang Chu  Female   153.9   
198  Shanghai Jiao Tong University     Senior   Chengmei Shen    Male   175.3   
199            Tsinghua University  Sophomore     Chunpeng Lv    Male   155.7   

     Weight Transfer  Test_Number   Test_Date Time_Record  
0      46.0        N            1   2019/10/5     0:04:34  
1      70.0        N            1    2019/9/4     0:04:20  
2      89.0        N            2   2019/9/12     0:05:22  
3      41.0        N            2    2020/1/3     0:04:08  
4      74.0        N            2   2019/11/6     0:05:22  
..      ...      ...          ...         ...         ...  
195    46.0        N            2  2019/10/17     0:04:31  
196    50.0        N            3   2019/9/22     0:04:03  
197    45.0        N            1    2020/1/5     0:04:48  
198    71.0        N            2    2020/1/7     0:04:58  
199    51.0        N            1   2019/11/6     0:05:05  

[200 rows x 10 columns]

In [4]:
df.groupby('Gender')['Height'].median()

Gender
Female    159.6
Male      173.4
Name: Height, dtype: float64

In [5]:
df.groupby(['School', 'Gender'])['Height'].mean()

School                         Gender
Fudan University               Female    158.776923
                               Male      174.212500
Peking University              Female    158.666667
                               Male      172.030000
Shanghai Jiao Tong University  Female    159.122500
                               Male      176.760000
Tsinghua University            Female    159.753333
                               Male      171.638889
Name: Height, dtype: float64

In [6]:
condition = df.Weight > df.Weight.mean()

In [7]:
df.groupby(condition)['Height'].mean()

Weight
False    159.034646
True     172.705357
Name: Height, dtype: float64

In [9]:
item = np.random.choice(list('abc'), df.shape[0])
item

array(['a', 'b', 'a', 'a', 'a', 'a', 'b', 'b', 'b', 'b', 'b', 'a', 'c',
       'b', 'a', 'c', 'b', 'b', 'a', 'b', 'a', 'a', 'c', 'c', 'a', 'c',
       'c', 'a', 'a', 'b', 'c', 'c', 'b', 'b', 'c', 'c', 'a', 'b', 'a',
       'c', 'c', 'b', 'b', 'c', 'a', 'b', 'c', 'c', 'c', 'a', 'c', 'b',
       'c', 'c', 'b', 'c', 'c', 'a', 'a', 'a', 'a', 'b', 'b', 'c', 'c',
       'a', 'a', 'c', 'b', 'c', 'c', 'c', 'b', 'b', 'b', 'a', 'c', 'c',
       'b', 'c', 'a', 'b', 'c', 'c', 'b', 'c', 'b', 'b', 'c', 'c', 'a',
       'c', 'c', 'c', 'c', 'a', 'c', 'b', 'b', 'b', 'a', 'c', 'a', 'a',
       'b', 'a', 'a', 'b', 'c', 'c', 'a', 'a', 'c', 'a', 'a', 'c', 'a',
       'c', 'a', 'c', 'b', 'b', 'c', 'a', 'a', 'c', 'b', 'c', 'b', 'c',
       'b', 'c', 'b', 'c', 'b', 'a', 'c', 'b', 'c', 'c', 'c', 'b', 'a',
       'c', 'a', 'b', 'c', 'a', 'c', 'a', 'a', 'c', 'c', 'c', 'c', 'b',
       'c', 'b', 'c', 'c', 'b', 'b', 'c', 'c', 'b', 'c', 'a', 'b', 'a',
       'b', 'b', 'a', 'b', 'a', 'a', 'c', 'b', 'c', 'a', 'c', 'b

In [10]:
df.groupby(item)['Height'].mean()

a    162.972549
b    162.782759
c    163.728378
Name: Height, dtype: float64

In [11]:
df.groupby([condition, item])['Height'].mean()

Weight   
False   a    158.000000
        b    159.737209
        c    159.134000
True    a    172.917647
        b    171.513333
        c    173.300000
Name: Height, dtype: float64

In [12]:
df.groupby(['School', 'Gender'])['Height'].mean()

School                         Gender
Fudan University               Female    158.776923
                               Male      174.212500
Peking University              Female    158.666667
                               Male      172.030000
Shanghai Jiao Tong University  Female    159.122500
                               Male      176.760000
Tsinghua University            Female    159.753333
                               Male      171.638889
Name: Height, dtype: float64

In [13]:
df.groupby([df['School'], df['Gender']])['Height'].mean()

School                         Gender
Fudan University               Female    158.776923
                               Male      174.212500
Peking University              Female    158.666667
                               Male      172.030000
Shanghai Jiao Tong University  Female    159.122500
                               Male      176.760000
Tsinghua University            Female    159.753333
                               Male      171.638889
Name: Height, dtype: float64

In [14]:
gb = df.groupby('Gender')['Height']
gb.idxmin()

Gender
Female    143
Male      199
Name: Height, dtype: int64

In [15]:
gb.quantile(0.95)

Gender
Female    166.8
Male      185.9
Name: Height, dtype: float64

In [16]:
gb = df.groupby('Gender')[['Height', 'Weight']]
gb.max()

Height  Weight
Gender                
Female   170.2    63.0
Male     193.9    89.0

In [18]:
gb.cummax().head()

Height  Weight
0   158.9    46.0
1   166.5    70.0
2   188.9    89.0
3     NaN    46.0
4   188.9    89.0

In [19]:
gb.filter(lambda x: x.shape[0] > 100)

Height  Weight
0     158.9    46.0
3       NaN    41.0
5     158.0    51.0
6     162.5    52.0
7     161.9    50.0
..      ...     ...
191   166.6    54.0
194   160.3    49.0
195   153.9    46.0
196   160.9    50.0
197   153.9    45.0

[141 rows x 2 columns]

In [23]:
gb = df.groupby(['Gender','Test_Number'])[['Height','Weight']]
gb.apply(lambda x: 0)

Gender  Test_Number
Female  1              0
        2              0
        3              0
Male    1              0
        2              0
        3              0
dtype: int64

In [24]:
df = pd.read_csv('../data/car.csv')
df.head(3)

Brand  Price Country  Reliability  Mileage   Type  Weight  Disp.  \
0   Eagle Summit 4   8895     USA          4.0       33  Small    2560     97   
1  Ford Escort   4   7402     USA          2.0       33  Small    2345    114   
2   Ford Festiva 4   6319   Korea          4.0       37  Small    1845     81   

    HP  
0  113  
1   90  
2   63

In [27]:
df.groupby('Country').filter(lambda x:x.shape[0]>2)

In [30]:
df.shape[0]

60

In [34]:
condition = ['Head']*20+['Mid']*20+['Tail']*20
df.groupby(condition)['Price'].mean()

Head     9069.95
Mid     13356.40
Tail    15420.65
Name: Price, dtype: float64

In [37]:
res = df.groupby('Type').agg({'Price': ['max'], 'HP':['min']})
res.columns = res.columns.map(lambda x:'_'.join(x))
res

Price_max  HP_min
Type                      
Compact      18900      95
Large        17257     150
Medium       24760     110
Small         9995      63
Sporty       13945      92
Van          15395     106

In [42]:
def normalize(s):
    s_min, s_max = s.min(), s.max()
    res = (s - s_min)/(s_max - s_min)
    return res

df.groupby('Type')['HP'].apply(normalize).head()

0    1.00
1    0.54
2    0.00
3    0.58
4    0.80
Name: HP, dtype: float64

In [43]:
df.groupby('Type')['HP'].transform(normalize).head()

0    1.00
1    0.54
2    0.00
3    0.58
4    0.80
Name: HP, dtype: float64

In [ ]:
class my_groupby:
    def __init__(self, my_df, group_cols):
        self.my_df = my_df.copy()
        self.groups = my_df[group_cols].drop_duplicates()
        if isinstance(self.groups, pd.Series):
            self.groups = self.groups.to_frame()

In [45]:
df1 = pd.DataFrame({'Name':['San Zhang','Si Li'], 'Age':[20,30]})
df1

Name  Age
0  San Zhang   20
1      Si Li   30

In [46]:
df2 = pd.DataFrame({'Name':['Si Li','Wu Wang'], 'Gender':['F','M']})
df2

Name Gender
0    Si Li      F
1  Wu Wang      M

In [48]:
df1.merge(df2, on='Name', how='left')
df1.merge(df2, on = 'Name', how = 'left')

Name  Age Gender
0  San Zhang   20    NaN
1      Si Li   30      F

In [49]:
df1 = pd.DataFrame({'df1_name':['San Zhang','Si Li'], 'Age':[20,30]})
df2 = pd.DataFrame({'df2_name':['Si Li','Wu Wang'], 'Gender':['F','M']})
df1.merge(df2, left_on='df1_name', right_on='df2_name', how='left')

df1_name  Age df2_name Gender
0  San Zhang   20      NaN    NaN
1      Si Li   30    Si Li      F

In [50]:
df1 = pd.DataFrame({'Name':['San Zhang'],'Grade':[70]})
df2 = pd.DataFrame({'Name':['San Zhang'],'Grade':[80]})
df1.merge(df2, on='Name', how='left', suffixes=['_Chinese','_Math'])

Name  Grade_Chinese  Grade_Math
0  San Zhang             70          80

In [51]:
df1 = pd.DataFrame({'Age':[20,30]}, index=pd.Series(['San Zhang','Si Li'],name='Name'))
df2 = pd.DataFrame({'Gender':['F','M']}, index=pd.Series(['Si Li','Wu Wang'],name='Name'))
df1.join(df2, how='left')

Age Gender
Name                 
San Zhang   20    NaN
Si Li       30      F

In [52]:
df1 = pd.DataFrame({'Age':[20,30]}, index=pd.Series(['San Zhang','Si Li'],name='Name'))
df2 = pd.DataFrame({'Gender':['F','M']}, index=pd.Series(['Si Li','Wu Wang'],name='Name'))

In [53]:
df1

Age
Name          
San Zhang   20
Si Li       30

In [54]:
df2

Gender
Name          
Si Li        F
Wu Wang      M

In [58]:
df1.join(df2, how = 'left') # join is by index

Age Gender
Name                 
San Zhang   20    NaN
Si Li       30      F

In [61]:
df1 = pd.DataFrame({'Name':['San Zhang','Si Li'], 'Age':[20,30]})
df2 = pd.DataFrame({'Name':['Wu Wang'], 'Age':[40]})
pd.concat([df1, df2], axis = 0)

Name  Age
0  San Zhang   20
1      Si Li   30
0    Wu Wang   40

In [62]:
pd.concat([df1, df2], axis=1, join='inner')

Name  Age     Name  Age
0  San Zhang   20  Wu Wang   40

In [63]:
df1 = pd.DataFrame({'Name':['San Zhang', 'Si Li', 'Wu Wang'],
                    'Age':[20, 21 ,21],
                    'Class':['one', 'two', 'three']})
df1

Name  Age  Class
0  San Zhang   20    one
1      Si Li   21    two
2    Wu Wang   21  three

In [64]:
df2 = pd.DataFrame({'Name':['San Zhang', 'Li Si', 'Wu Wang'],
                    'Age':[20, 21 ,21],
                    'Class':['one', 'two', 'Three']})
df2

Name  Age  Class
0  San Zhang   20    one
1      Li Si   21    two
2    Wu Wang   21  Three

In [67]:
df_com = df1.compare(df2)

In [68]:
df_com.replace(np.NaN, 'Same')

Name         Class       
    self  other   self  other
1  Si Li  Li Si   Same   Same
2   Same   Same  three  Three

In [69]:
df1.compare(df2, keep_shape=True)

Name         Age        Class       
    self  other self other   self  other
0    NaN    NaN  NaN   NaN    NaN    NaN
1  Si Li  Li Si  NaN   NaN    NaN    NaN
2    NaN    NaN  NaN   NaN  three  Three

YYYY State           COUNTY  SubstanceName  DrugReports
0  2010    VA         ACCOMACK   Propoxyphene            1
1  2010    OH            ADAMS       Morphine            9
2  2010    PA            ADAMS      Methadone            2
3  2010    VA  ALEXANDRIA CITY         Heroin            5
4  2010    PA        ALLEGHENY  Hydromorphone            5

In [73]:
date = pd.date_range('20200412', '20201116').to_series()
date = date.dt.month.astype('string').str.zfill(2) +'-'+ date.dt.day.astype('string').str.zfill(2) +'-'+ '2020'
date = date.tolist()
date

['04-12-2020',
 '04-13-2020',
 '04-14-2020',
 '04-15-2020',
 '04-16-2020',
 '04-17-2020',
 '04-18-2020',
 '04-19-2020',
 '04-20-2020',
 '04-21-2020',
 '04-22-2020',
 '04-23-2020',
 '04-24-2020',
 '04-25-2020',
 '04-26-2020',
 '04-27-2020',
 '04-28-2020',
 '04-29-2020',
 '04-30-2020',
 '05-01-2020',
 '05-02-2020',
 '05-03-2020',
 '05-04-2020',
 '05-05-2020',
 '05-06-2020',
 '05-07-2020',
 '05-08-2020',
 '05-09-2020',
 '05-10-2020',
 '05-11-2020',
 '05-12-2020',
 '05-13-2020',
 '05-14-2020',
 '05-15-2020',
 '05-16-2020',
 '05-17-2020',
 '05-18-2020',
 '05-19-2020',
 '05-20-2020',
 '05-21-2020',
 '05-22-2020',
 '05-23-2020',
 '05-24-2020',
 '05-25-2020',
 '05-26-2020',
 '05-27-2020',
 '05-28-2020',
 '05-29-2020',
 '05-30-2020',
 '05-31-2020',
 '06-01-2020',
 '06-02-2020',
 '06-03-2020',
 '06-04-2020',
 '06-05-2020',
 '06-06-2020',
 '06-07-2020',
 '06-08-2020',
 '06-09-2020',
 '06-10-2020',
 '06-11-2020',
 '06-12-2020',
 '06-13-2020',
 '06-14-2020',
 '06-15-2020',
 '06-16-2020',
 '06-17-20

In [75]:
L = []
for d in date:
    df = pd.read_csv('../data/us_report/' + d + '.csv', index_col='Province_State')
    data = df.loc['New York', ['Confirmed','Deaths','Recovered','Active']]
    L.append(data.to_frame().T)
res = pd.concat(L)
res.index = date
res.head()

Confirmed Deaths Recovered  Active
04-12-2020    189033   9385     23887  179648
04-13-2020    195749  10058     23887  185691
04-14-2020    203020  10842     23887  192178
04-15-2020    214454  11617     23887  202837
04-16-2020    223691  14832     23887  208859

In [ ]:
def join(df1, df2, how = 'left'):
    res_col = df1.columns.tolist() 

In [76]:
df = pd.read_csv('../data/learn_pandas.csv', usecols = ['Grade', 'Name', 'Gender', 'Height', 'Weight', 'Transfer'])
df.isna().head()

Grade   Name  Gender  Height  Weight  Transfer
0  False  False   False   False   False     False
1  False  False   False   False   False     False
2  False  False   False   False   False     False
3  False  False   False    True   False     False
4  False  False   False   False   False     False

In [78]:
df.isna().mean()

Grade       0.000
Name        0.000
Gender      0.000
Height      0.085
Weight      0.055
Transfer    0.060
dtype: float64

In [79]:
df[df.Height.isna()]

Grade          Name  Gender  Height  Weight Transfer
3    Sophomore  Xiaojuan Sun  Female     NaN    41.0        N
12      Senior      Peng You  Female     NaN    48.0      NaN
26      Junior     Yanli You  Female     NaN    48.0        N
36    Freshman  Xiaojuan Qin    Male     NaN    79.0        Y
60    Freshman    Yanpeng Lv    Male     NaN    65.0        N
91   Sophomore   Yanfeng Han    Male     NaN     NaN        N
98   Sophomore  Xiaojuan Chu    Male     NaN    68.0        N
102     Junior  Chengli Zhao    Male     NaN     NaN      NaN
111   Freshman    Gaoquan Xu  Female     NaN    52.0        N
130     Senior      Mei Feng  Female     NaN    51.0        N
133   Freshman   Gaojuan Qin  Female     NaN    41.0        N
145     Junior   Gaoquan Chu  Female     NaN    51.0        N
152     Junior   Chengli Sun    Male     NaN    62.0        N
154     Junior   Yanpeng Han  Female     NaN    44.0        N
178  Sophomore        Li Qin    Male     NaN    76.0        N
181  Sophomore   Yanjuan You    Male     NaN    55.0        N
186   Freshman  Yanjuan Zhao  Female     NaN    53.0        N

In [80]:
sub_set = df[['Height', 'Weight', 'Transfer']]
df[sub_set.isna().all(1)] # 全部缺失

Grade          Name Gender  Height  Weight Transfer
102  Junior  Chengli Zhao   Male     NaN     NaN      NaN

In [81]:
df[sub_set.isna().any(1)].head() # 至少有一个缺失

Grade           Name  Gender  Height  Weight Transfer
3   Sophomore   Xiaojuan Sun  Female     NaN    41.0        N
9      Junior        Juan Xu  Female   164.8     NaN        N
12     Senior       Peng You  Female     NaN    48.0      NaN
21     Senior  Xiaopeng Shen    Male   166.0    62.0      NaN
26     Junior      Yanli You  Female     NaN    48.0        N

In [82]:
df[sub_set.notna().all(1)].head() # 没有缺失

Grade            Name  Gender  Height  Weight Transfer
0   Freshman    Gaopeng Yang  Female   158.9    46.0        N
1   Freshman  Changqiang You    Male   166.5    70.0        N
2     Senior         Mei Sun    Male   188.9    89.0        N
4  Sophomore     Gaojuan You    Male   174.0    74.0        N
5   Freshman     Xiaoli Qian  Female   158.0    51.0        N

In [89]:
res = df.dropna(1, thresh=df.shape[0]-15) # 身高被删除
res.head()

Grade            Name  Gender  Weight Transfer
0   Freshman    Gaopeng Yang  Female    46.0        N
1   Freshman  Changqiang You    Male    70.0        N
2     Senior         Mei Sun    Male    89.0        N
3  Sophomore    Xiaojuan Sun  Female    41.0        N
4  Sophomore     Gaojuan You    Male    74.0        N

In [85]:
res = df.dropna(how = 'any', subset = ['Height', 'Weight'])
res

Grade            Name  Gender  Height  Weight Transfer
0     Freshman    Gaopeng Yang  Female   158.9    46.0        N
1     Freshman  Changqiang You    Male   166.5    70.0        N
2       Senior         Mei Sun    Male   188.9    89.0        N
4    Sophomore     Gaojuan You    Male   174.0    74.0        N
5     Freshman     Xiaoli Qian  Female   158.0    51.0        N
..         ...             ...     ...     ...     ...      ...
195     Junior    Xiaojuan Sun  Female   153.9    46.0        N
196     Senior         Li Zhao  Female   160.9    50.0        N
197     Senior  Chengqiang Chu  Female   153.9    45.0        N
198     Senior   Chengmei Shen    Male   175.3    71.0        N
199  Sophomore     Chunpeng Lv    Male   155.7    51.0        N

[174 rows x 6 columns]

In [90]:
s = pd.Series([np.nan, 1, np.nan, np.nan, 2, np.nan], list('aaabcd'))
s

a    NaN
a    1.0
a    NaN
b    NaN
c    2.0
d    NaN
dtype: float64

In [91]:
s.fillna(method='ffill') # 用前面的值向后填充

a    NaN
a    1.0
a    1.0
b    1.0
c    2.0
d    2.0
dtype: float64

In [92]:
s.fillna(s.mean()) # value为标量

a    1.5
a    1.0
a    1.5
b    1.5
c    2.0
d    1.5
dtype: float64

In [93]:
s.fillna({'a': 100, 'd': 200}) # 通过索引映射填充的值

a    100.0
a      1.0
a    100.0
b      NaN
c      2.0
d    200.0
dtype: float64

In [94]:
df.groupby('Grade')['Height'].transform(lambda x: x.fillna(x.mean())).head()

0    158.900000
1    166.500000
2    188.900000
3    163.075862
4    174.000000
Name: Height, dtype: float64

In [96]:
df.groupby('Grade')['Height'].apply(lambda x: x.fillna(x.mean())).head()

0    158.900000
1    166.500000
2    188.900000
3    163.075862
4    174.000000
Name: Height, dtype: float64

In [97]:
s = pd.Series([np.nan, np.nan, 1, np.nan, np.nan, np.nan, 2, np.nan, np.nan])
s.values

array([nan, nan,  1., nan, nan, nan,  2., nan, nan])

In [98]:
s = pd.Series(['abcd', 'efg', 'hi'])
s.str

In [99]:
s.str.upper()

0    ABCD
1     EFG
2      HI
dtype: object

In [101]:
var = 'abcd'
str.upper(var) # Python内置str模块

'ABCD'

In [102]:
var[-1: 0: -1]

'dcb'

In [105]:
s = pd.Series([{1: 'temp_1', 2: 'temp_2'}, ['a', 'b'], 0.5, 'my_string'])
s.str[1]

0    temp_1
1         b
2       NaN
3         y
dtype: object